-- Setup Users Script
-- NOTE: Login credentials are NOT read from this table.
-- The app authenticates via the APP_USERS environment variable (.env.local).
-- Users in this table are created automatically on first login from APP_USERS.
--
-- This script is for manually pre-creating users (e.g. migration). You'll need
-- to generate password hashes using bcrypt:
--   Option 1: https://bcrypt-generator.com/
--   Option 2: require('bcryptjs').hashSync('yourpassword', 12)
--
-- Example (replace with your actual hashed passwords):
-- INSERT INTO users (username, password_hash, display_name) VALUES
-- ('dad', '$2a$12$YourHashedPasswordHere', 'Dad'),
-- ('mom', '$2a$12$YourHashedPasswordHere', 'Mom')
-- ON CONFLICT (username) DO NOTHING;
